class Params_Decision:

    MONITOR_TIME = 150
    REDUCED_MONITORING_TIME = 100
    UPDATE_FREQUENCY = 5
    CLOSEST_HEAD_BOUNDARY = 5
    DEPTH = 6


class Params_Automat:

    HEAD_DIST_AVG_AGGRESSIVE = 4
    HEAD_DIST_AVG_HUNGRY = 5
    ENEMY_HEALTH_BOUNDARY = 20
    MONITOR_LENGTH = 20
    MONITOR_DISTANCE = 10
    PATH_LENGTH = 10

    MY_HEALTH_BOUNDARY = 25
    ROUND_NUMBER_BOUNDARY = 150
    ENEMIES_ALIVE = 3


class Params_MovementProfile:

    FOOD_PROFILE_DIST_BOUNDARY = 10
    HEAD_PROFILE_DIST_BOUNDARY = 15


class Params_Anxious:

    ALPHA_DISTANCE_SNAKE = 3
    BETA_DISTANCE_CORNERS = 2
    GAMMA_DISTANCE_FOOD = 3
    THETA_DISTANCE_MID = 7
    PHI_ESCAPE_DIRECTION = 5


class Params_ActionPlan:

    SNAKE_RADIUS = 5


class Params_ValidActions:

    DIST_TO_ENEMY = 15
    BODY_VALUE = 3
    HEAD_VALUE = 25
    AREA_VALUE = 5
