# TODO: Train Parameters with genetic algorithm


class Params_Decision:

    MONITOR_TIME = 150
    REDUCED_MONITORING_TIME = 100
    UPDATE_FREQUENCY = 5
    CLOSEST_HEAD_BOUNDARY = 5
    BOARD_11 = 0
    BOARD_15 = 0
    BOARD_18 = 0


class Params_Automat:

    HEAD_DIST_AVG_AGGRESSIVE = 4
    HEAD_DIST_AVG_HUNGRY = 5
    ENEMY_HEALTH_BOUNDARY = 20
    MONITOR_LENGTH = 20
    MONITOR_DISTANCE = 10
    PATH_LENGTH = 10

    MY_HEALTH_BOUNDARY = 25
    ROUND_NUMBER_BOUNDARY = 150
    ENEMIES_ALIVE = 3


class Params_MovementProfile:

    FOOD_PROFILE_DIST_BOUNDARY = 10
    HEAD_PROFILE_DIST_BOUNDARY = 15


class Params_Anxious:

    ALPHA_DISTANCE_SNAKE = 5
    BETA_DISTANCE_CORNERS = 2
    GAMMA_DISTANCE_FOOD = 7
    THETA_DISTANCE_MID = 7
    PHI_ESCAPE_DIRECTION = 1
    PSI_BORDER_VALUE = 1


class Params_ActionPlan:

    SNAKE_RADIUS = 5


class Params_ValidActions:

    DEPTH = 5
    DIST_TO_ENEMY = 15
    BODY_VALUE = 10
    HEAD_VALUE = 50
    AREA_VALUE = 5
    FOOD_BOUNDARY = 25
